### ISSUE TITLE
Get flow control working

### ISSUE THREAD

**Issue by ghost** [digistump/DigiFi#7]
@ags131
Flow control merge didn't work - if I put the USART files in cores/digix replacing those already there it threw a page of errors, did I not understand that correctly? The changes are still present in the latest version, just commented out where necessary to keep it working. I also changed it to be disabled by default since the DigiX ships with it disabled on the WiFi module.

I also changed URLEncode back to accepting a string - since it outputs a string, it seems to me it should accept one (it broke the KeyboardTweet example) - very open to hear why you changed it to char\* and reconsider - I should have caught that in the first merge - sorry!

No rush, I know your busy, no pressure intended, just putting these thoughts down while fresh and seeing if I made some stupid mistake/misunderstanding.

**Comment by AlinaNova21** [comment]
I believe the URLEncode change was because Arduino pitched a fit about passing the String class around at one point, but that error may have been triggered by another part of code too. Anyway, that was the only reason it changed, as for flow control, I will try to mess with it more next week, things should be settled down some by then, I haven't even got the second DigiX out of the static bag yet brain seems to think it shouldn't concentrate once I get home lately. :)

**Comment by digistump** [comment]
If any issues with passing string around crop up again I'll have to look into them and maybe make some changes to how things get passed around.

No problem if it takes some time - I just did a vendor appearance at a conference, then my wife and I got the flu (thankfully our baby did not), and now I'm trying to catch back up on my day jobs - so I certainly understand the feeling! I'll mess with it if I get a chance before you, but that is unlikely as we prepare for the arrival of 2,000 DigiXs

Thanks for all of your contributions so far!

**Comment by AlinaNova21** [comment]
No problem, I enjoy doing this stuff, just wish I had more time and funds
for it :)

**Comment by AlinaNova21** [comment]
Fixed :) https://github.com/digistump/DigiFi/pull/8

**Comment by digistump** [comment]
Thanks!
